parameters:
#    najdah_etab.example.class: Najdah\EtabBundle\Example

services:
#    najdah_etab.example:
#        class: %najdah_etab.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
