jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Najdah\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN_POMPIER:   ROLE_POMPIER
        ROLE_ADMIN_POLICIER:  ROLE_POLICIER
        ROLE_ADMIN:       [ROLE_ADMIN_POLICIER, ROLE_ADMIN_POMPIER, ROLE_UTILISATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true
        
        main_inter:
            pattern: ^/Inter/*
            anonymous: true

        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /login
            remember_me:
                key: %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
