<?php

namespace Najdah\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CitoyenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitoyenRepository extends EntityRepository
{

    //------------------------------------  Nombre de tous les citoyen
    public function getNombreAllCitoyen(){
        //getDoctrine()->getManager()
        $query =$this->getEntityManager()
            ->createQuery('SELECT count(c) from NajdahUserBundle:Citoyen c');

        $nbr=$query->getSingleScalarResult();
        return $nbr;
    }
}
