<?php

namespace Najdah\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CitoyenController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Najdah\UserBundle\Controller\CitoyenController();
        return $instance;
    }
}
