<?php

namespace Najdah\EtabBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EtablissementController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Najdah\EtabBundle\Controller\EtablissementController();
        return $instance;
    }
}
