<?php

namespace Najdah\EtabBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEtablissementRepository extends EntityRepository
{
}
