<?php

namespace Najdah\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtatDeclarationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatDeclarationRepository extends EntityRepository
{
}
